# The version number of this file format
meta:
  version: 1.0.0
# The front end versions that support this file format version 
frontend:
  version: ">=1.0.2"
# The framework version this store file applies to
framework:
  version: =3.0.6
  github-tag: 'v3.0.6' # Or branch
  github-sha: 720117b4598fbd027e3eb5383d2716342ce67403
# When this store was created
timestamp: ~
# Which certificate signed the modules in this store
signer: default
supported-languages:
  - en
# The extensions defined in this store
extensions:
# The list of extensions
  list:
# Plugins
    - definition:
        name: AI-Tournament-Maps
        version: 1.0.0
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/extension-AI-Tournament-Maps
          github-sha: ae9ffcc35f7ef491fed787be1d75fca979670b81
          github-tag: main
    - definition:
        name: Aggressive-AI-Behaviour
        version: 1.4.0
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/extension-Aggressive-AI-Behaviour
          github-sha: 137f71f11a8b6caebfe166ce6156a18b07749718
          github-tag: main
    - definition:
        name: Aggressive-AI-Behaviour-Applied
        version: 1.4.0
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/extension-Aggressive-AI-Behaviour-Applied
          github-sha: 26494f52da1d2c222acfeb05545ddc72da8e0c42
          github-tag: main
    - definition:
        name: ApeX-AI-Behaviour
        version: 1.4.0
        type: plugin
      contents:
        source:
          method: github
          url: Xander10alpha/extension-ApeX-AI-Behaviour
          github-sha: 46048311f4230de20c603d0b966d8991678a1a6e
          github-tag: main
    - definition:
        name: ApeX-AI-Behaviour-Applied
        version: 1.4.0
        type: plugin
      contents:
        source:
          method: github
          url: Xander10alpha/extension-ApeX-AI-Behaviour-Applied
          github-sha: 2568968ffd30e7c3590012bf45612adf6ca44c6d
          github-tag: main
    - definition:
        name: Vanilla-Interpretation-Castles
        version: 1.0.2
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/extension-Vanilla-Interpretation-Castles
          github-sha: eef88bc98e462c6ee3a288e03f13dc3b3702e2e6
          github-tag: main
    - definition:
        name: Vanilla-Interpretation-Castles-Applied
        version: 1.0.2
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/extension-Vanilla-Interpretation-Castles-Applied
          github-sha: 1b9e4a863c20f991fae3eb1b236f010d17ca900f
          github-tag: main
    - definition:
        name: Vanilla-Retraced-Unlocked
        version: 1.0.2
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/Vanilla-Retraced
          github-sha: 5aea02a5987bef1759e3df50c7bec86084ee7496
          github-tag: main
    - definition:
        name: ucp2-ai-files
        version: 2.15.1
        type: plugin
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-ucp2-ai-files
          github-sha: 481d745f8960c44e6de16b6200d66af04cc89b20
          github-tag: main
    - definition:
        name: ucp2-aic-patch
        version: 2.15.1
        type: plugin
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-ucp2-aic-patch
          github-sha: 3d39204e179bf848896fd59b6efae9b5a959123c
          github-tag: main
    - definition:
        name: ucp2-evrey-aiv
        version: 2.15.1
        type: plugin
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-ucp2-evrey-aiv
          github-sha: d1c5007f19103917947682755b7d4bce394c9243
          github-tag: main
    - definition:
        name: ucp2-legacy-defaults
        version: 2.15.1
        type: plugin
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-ucp2-legacy-defaults
          github-sha: 68ef49205cc604311f230ef462b0cebf18e74e9d
          github-tag: main
    - definition:
        name: ucp2-tatha-aiv
        version: 2.15.1
        type: plugin
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-ucp2-tatha-aiv
          github-sha: 5c9775b6dd90f9be77b50f30183c3c69a2467ee9
          github-tag: main
    - definition:
        name: ucp2-vanilla-fixed-aiv
        version: 2.15.1
        type: plugin
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-ucp2-vanilla-fixed-aiv
          github-sha: 2aac2f860ed81a0f38212e4ae953d53867f5f396
          github-tag: main
    - definition:
        name: Legends-Of-The-Orient
        version: 3.0.3
        type: plugin
      contents:
        source:
          method: github
          url: CrusaderPilaw/extension-Legends-of-the-Orient
          github-sha: 1e9a785e65107345403f28fb40d365d6df8001ab
          github-tag: main
    - definition:
        name: Legends-Of-The-Orient-AI
        version: 3.0.2
        type: plugin
      contents:
        source:
          method: github
          url: CrusaderPilaw/extension-Legends-of-the-Orient-AI
          github-sha: 2fd8840c40264a53110fc21e9060d098192b1049
          github-tag: main
    - definition:
        name: Fiery-Ladies
        type: plugin
        version: 0.4.0
      contents:
        source:
          method: github
          url: ByBurton/extension-fiery-ladies
          github-sha: 39bc99c47eee03311440b37882c68ed442a4ef73
          github-tag: main
    - definition:
        name: Fiery-Ladies-AI
        type: plugin
        version: 0.4.0
      contents:
        source:
          method: github
          url: ByBurton/extension-fiery-ladies-ai
          github-sha: 5567282108b89387bd2bc7016d67995c7cd0fcb4
          github-tag: main
    - definition:
        name: Schlossgespenst-KI
        type: plugin
        version: 1.0.2
      contents:
        source:
          method: github
          url: Schlossgespensty/Schlossgespenst-KI
          github-sha: 8a843337a6a1aea895a4b6f063f1d65ad5d3a4be
          github-tag: main
    - definition:
        name: Schlossgespenst-KI-files
        type: plugin
        version: 1.0.4
      contents:
        source:
          method: github
          url: Schlossgespensty/Schlossgespenst-KI-files
          github-sha: 362eadd1d3f5f84d660ffaa2c101f67c95fb2677
          github-tag: main
    - definition:
        name: ConqueringChristmas
        version: 1.0.1
        type: plugin
      contents:
        source:
          method: github
          url: Monsterfisch/ConqueringChristmas_-Stronghold1_textures-with-snow-
          github-sha: cc03cf4d47d06657402365987a7699c2cbd27e25
          github-tag: main
    - definition:
        name: ConqueringEurope
        version: 1.0.0
        type: plugin
      contents:
        source:
          method: github
          url: Monsterfisch/ConqueringEurope_-Stronghold1_textures-
          github-sha: fb703ff23c4f05b761fbc3dc0dcdaab108d8ff3f
          github-tag: main
    - definition:
        name: Kirito-Kun
        version: 1.0.0
        type: plugin
      contents:
        source:
          method: github
          url: Xander10alpha/extension-Kirito-Kun-AI
          github-sha: 1b24f0b71d411f79ccb028ce88055230f57de677
          github-tag: main
    - definition:
        name: Ascension-AI-Balance
        version: 1.0.6
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/Ascension
          github-sha: 184749f1432b8330848abc64faf87a4d83090c29
          github-tag: ucp3-ascension
          location: extension-Ascension-AI-Balance   
    - definition:
        name: Ascension-Balance
        version: 1.0.3
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/Ascension
          github-sha: 184749f1432b8330848abc64faf87a4d83090c29
          github-tag: ucp3-ascension
          location: extension-Ascension-Balance
    - definition:
        name: Ascension-AI
        version: 1.0.0
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/Ascension
          github-sha: 184749f1432b8330848abc64faf87a4d83090c29
          github-tag: ucp3-ascension
          location: extension-Ascension-AI
    - definition:
        name: Ascension-Multiplayer
        version: 1.0.4
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/Ascension
          github-sha: 184749f1432b8330848abc64faf87a4d83090c29
          github-tag: ucp3-ascension
          location: extension-Ascension-Multiplayer
    - definition:
        name: Ascension-Maps
        version: 1.0.1
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/Ascension
          github-sha: 184749f1432b8330848abc64faf87a4d83090c29
          github-tag: ucp3-ascension
          location: extension-Ascension-Maps
    - definition:
        name: Community-Paket-Files
        version: 1.0.1
        type: plugin
      contents:
        source:
          method: github
          url: Nevikov/Community-Paket-UCP3
          github-sha: 1e11f99033c598567145a6597f733945881ba70a
          github-tag: main
          location: Community-Paket-Files
    - definition:
        name: Community-Paket
        version: 1.0.1
        type: plugin
      contents:
        source:
          method: github
          url: Nevikov/Community-Paket-UCP3
          github-sha: 1e11f99033c598567145a6597f733945881ba70a
          github-tag: main
          location: Community-Paket
    - definition:
        name: Die-neuen-Herrscher
        version: 1.0.0
        type: plugin
      contents:
        source:
          method: github
          url: Hacksuelze/Die-neuen-Herrscher
          github-sha: 4a02e6e6cefa730725473c881960f1324c410ffe
          github-tag: main
    - definition:
        name: Die-neuen-Herrscher-KI-Files
        version: 1.0.0
        type: plugin
      contents:
        source:
          method: github
          url: Hacksuelze/Die-neuen-Herrscher-KI
          github-sha: 080d56188175cb36699b8b980e1d73543dc01fdb
          github-tag: main
    - definition:
        name: Ascension-AI-Tournament
        version: 3.0.0
        type: plugin
      contents:
        source:
          method: github
          url: Krarilotus/Ascension-AI-Tournament
          github-sha: d15108d47bf50c358077334d39e095f0d5227720
          github-tag: main
# Modules
    - definition:
        name: aiSwapper
        version: 1.1.0
        type: module
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-aiSwapper
          github-sha: f779b9a2bd5a9691b8bbfc9459af019b5ad29f85
          github-tag: main
    - definition:
        name: aicloader
        version: 1.1.1
        type: module
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-aicloader
          github-sha: a6d1a960f9e96f4e815d601ac5dee2a736659da2
          github-tag: main
    - definition:
        name: aivloader
        version: 1.0.0
        type: module
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-aivloader
          github-sha: e5afeb5771b813cf1f594806f16b53c1c3d476c5
          github-tag: main
    - definition:
        name: files
        version: 1.1.0
        type: module
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-files
          github-sha: 27b1a19f22c3cc53c1641f593d9f82fa71dfd029
          github-tag: main
    - definition:
        name: files
        version: 1.2.0
        type: module
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-files
          github-sha: c77b07577aef94d594b2454cbde8a81f9e15e4d4
          github-tag: main
    - definition:
        name: gmResourceModifier
        version: 0.2.0
        type: module
      contents:
        source:
          method: github
          url: TheRedDaemon/ucp_gmResourceModifier
          github-sha: 019039afcb29f3806aa30c7157ae5a1253c06673
          github-tag: main
    - definition:
        name: graphicsApiReplacer
        version: 1.2.0
        type: module
      contents:
        source:
          method: github
          url: TheRedDaemon/ucp_graphicsApiReplacer
          github-sha: 14ef8ddf5b55d57778c2a7cf7b0e522bc045a191
          github-tag: main
    - definition:
        name: maploader
        version: 1.0.0
        type: module
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-maploader
          github-sha: 658f9e73feb1ff4b4da3e45f236cb2ff0c1d8d32
          github-tag: main
    - definition:
        name: startResources
        version: 1.0.0
        type: module
      contents:
        source:
          method: github
          url: gynt/ucp_startResources
          github-sha: 1942ce1e1d55ea4499a997fbecf719f882c9f715
          github-tag: main
    - definition:
        name: textResourceModifier
        version: 0.3.0
        type: module
      contents:
        source:
          method: github
          url: TheRedDaemon/ucp_textResourceModifier
          github-sha: 5ab58faf03c47c16f7b23cb6bc651317edf23728
          github-tag: main
    - definition:
        name: ucp2-legacy
        version: 2.15.1
        type: module
      contents:
        source:
          method: github
          url: UnofficialCrusaderPatch/extension-ucp2-legacy
          github-sha: 04e826d00f1a5f8a623e15acffc743f115ee7fb1
          github-tag: main
    - definition:
        name: winProcHandler
        version: 0.2.0
        type: module
      contents:
        source:
          method: github
          url: TheRedDaemon/ucp_winProcHandler
          github-sha: aa39902c15dc63fc159ade35ca4907ac334e9724
          github-tag: main
    - definition:
        name: running-units
        version: 1.0.1
        type: module
      contents:
        source:
          method: github
          url: gynt/ucp-extension-running-units
          github-sha: add648dfda85f5c6c36e8ca1b2c0e4f798a034f4
          github-tag: main
    - definition:
        name: rebalancer
        version: 1.0.6
        type: module
      contents:
        source:
          method: github
          url: CIO61/rebalancer
          github-sha: 14af1a3239e2a912de6e19b1a406917583acca2e
          github-tag: master
    - definition:
        name: citizens
        version: 1.0.0
        type: module
      contents:
        source:
          method: github
          url: gynt/ucp-extension-citizens
          github-sha: 74b4b610212110f4bd21195efb9d35b0d0c90f04
          github-tag: main

   
