$REPO = "UnofficialCrusaderPatch/UCP3-extensions-store"

$branch = git rev-parse --abbrev-ref HEAD
$tag = "v$branch"
$releaseTags = gh --repo $REPO release list --json tagName | ConvertFrom-Json | ForEach-Object { $_.tagName }

$exists = ($releaseTags | Where-Object {$_ -eq "$tag"} ) -ne $null

if ($exists) {
  Write-Output "Release already exists: $tag, overwriting files"
  gh release upload --repo $REPO --clobber $tag "./build/store.yml" (Get-Item .\build\extensions\*.zip)
} else {
  Write-Output "Release does not already exist: $tag, uploading as new files"
  gh release create --repo $REPO --target $branch $tag "./build/store.yml"  (Get-Item .\build\extensions\*.zip) --title "Store for $branch" --notes "This release is generated by a script"
}